### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by qrpike** [BTrDB/btrdb-server#40]
I have a kubernetes cluster with ceph as well. Are there any docs to getting btrdb setup?

Also what is the state of the project? Is it alpha / beta / or pretty stable?

Thanks!

**Comment by pingthings** [comment]
The project is currently in v4 release.  It has been very stable even under the v3 release.   We are currently working on docs for the installation especially since Kubernetes is in a state of constant flux.  We are currently chasing down some issues with the current 1.6 release from K8

**Comment by qrpike** [comment]
@pingthings Great to hear, we're still on 1.5.4 so hopefully the upgrade isn't too bad lol Let me know if I can help in any way. Thanks again for the great project!

**Comment by skarlsson** [comment]
I have a kubernetes cluster running 1.8 created by rancher. I followed or adapted the installation procedure in smartgridstore. I think I got etcd running. However the createdb.job.yaml seems to fail. Are there any recent installation docs?

**Comment by pingthings** [comment]
What version of BTrDB are you using from GitHub?

**Comment by skarlsson** [comment]
wget https://github.com/BTrDB/smartgridstore/releases/download/v4.7.0/mfgen
...
It felt like a good starting point to get something running - I'm open to suggestions if that was a bad choice! I've been doing other stuff today but I'm thinking that the createdb job cannot connect to etcd...

**Comment by pingthings** [comment]
That was the correct choice..  there are additional small details that have yet to find their proper place in the documentation.   Can you tell me what PV's and PVC's you have for the SGS namespace?

**Comment by skarlsson** [comment]
sudo ceph osd pool create btrdb_staging 16
sudo ceph osd pool create btrdb_data 16
sudo ceph osd pool create btrdb_hot 16
```
cat > storage_etcd_backup_gce_pd.yml <<EOF
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: etcd-backup-gce-pd
  annotations:
    "storageclass.beta.kubernetes.io/is-default-class": "true"
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.0.1.160:6789, 10.0.1.161:6789, 10.0.1.162:6789
  adminId: admin
  adminSecretName: ceph-rbd-secret
  adminSecretNamespace: sgs
  pool: kube
  userId: admin
  userSecretName: ceph-rbd-secret
EOF

kubectl apply -f storage_etcd_backup_gce_pd.yml

```
